# Generated by Django 4.0.4 on 2022-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_message_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
